name: google_maps_integration
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  after_layout: ^1.2.0
  chunked_stream: ^1.4.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.3
  google_maps_flutter_android: ^2.4.3
  google_maps_flutter_ios: ^2.1.13
  google_maps_flutter_platform_interface: ^2.2.5
  http: ^0.13.5
  keyboard_dismisser: ^3.0.0
  location: ^4.4.0
  modal_bottom_sheet: ^2.1.2
  permission_handler: ^10.2.0
  place_picker: ^0.10.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/markers/android/
    - assets/markers/ios/
    - assets/styles/
